// Code generated by gen_twirpjs v0.0.4, DO NOT EDIT.
// source: ../twirper.proto
import newTwirpClient from 'twirpjs'
import { twirper } from './twirper.pb'

/**
 * Create a new twirper.Twirper client
 */
export function newTwirperClient(hostURL, opts = {}) {
	return newTwirpClient(hostURL, {
		serviceRoute: 'twirper.Twirper',
		serviceClass: twirper.Twirper,
		streamingRespMethods: ["Repeat"],
		...opts
	})
}

