// Code generated by protoc-gen-go. DO NOT EDIT.
// source: twirper.proto

/*
Package twirper is a generated protocol buffer package.

It is generated from these files:
	twirper.proto

It has these top-level messages:
	EchoReq
*/
package twirper

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Request type for the Echo RPC (also the response, because echo)
type EchoReq struct {
	// Message will be echoed back in the EchoResp
	Message string `protobuf:"bytes,1,opt,name=Message" json:"Message,omitempty"`
}

func (m *EchoReq) Reset()                    { *m = EchoReq{} }
func (m *EchoReq) String() string            { return proto.CompactTextString(m) }
func (*EchoReq) ProtoMessage()               {}
func (*EchoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EchoReq) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*EchoReq)(nil), "twirper.EchoReq")
}

func init() { proto.RegisterFile("twirper.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x29, 0xcf, 0x2c,
	0x2a, 0x48, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x94, 0xb9,
	0xd8, 0x5d, 0x93, 0x33, 0xf2, 0x83, 0x52, 0x0b, 0x85, 0x24, 0xb8, 0xd8, 0x7d, 0x53, 0x8b, 0x8b,
	0x13, 0xd3, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x23, 0x53, 0x2e, 0xf6,
	0x10, 0x88, 0x7a, 0x21, 0x2d, 0x2e, 0x16, 0x90, 0x7a, 0x21, 0x01, 0x3d, 0x98, 0x81, 0x50, 0xed,
	0x52, 0x18, 0x22, 0x4e, 0x9c, 0x51, 0x30, 0x6b, 0x92, 0xd8, 0xc0, 0xd6, 0x1a, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x02, 0x27, 0x93, 0x81, 0x87, 0x00, 0x00, 0x00,
}
